config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  scope module: :customers do
    resource :account, only: :show

    resources :transactions, only: %i[new create]
  end

  # Defines the root path route ("/")
  root "customers/account#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_many :received_transactions,
           class_name: "Transaction",
           inverse_of: :receiver,
           foreign_key: :receiver_id

  has_many :sent_transactions,
           class_name: "Transaction",
           inverse_of: :sender,
           foreign_key: :sender_id

  validates :balance_cents, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  monetize :balance_cents

  def transactions
    sent_transactions.or(received_transactions).order(created_at: :desc)
  end

  def update_balance_atomic!(amount:)
    lock!
    self.balance += amount
    save!
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  TYPE = %w[credit transfer].freeze

  belongs_to :sender,
             class_name: "Customer",
             inverse_of: :sent_transactions,
             optional: true

  belongs_to :receiver,
             class_name: "Customer",
             inverse_of: :received_transactions

  scope :credits, -> { where(transaction_type: "credit") }
  scope :transfers, -> { where(transaction_type: "transfer") }

  validates :transaction_type, inclusion: { in: TYPE }
  validates :amount_cents, numericality: { greater_than: 0, only_integer: true }
  validate :validate_sender_balance, if: :sender

  monetize :amount_cents, with_model_currency: :currency

  after_create :after_create_recalculate_sender_receiver_balances

  private

  def after_create_recalculate_sender_receiver_balances
    ActiveRecord::Base.transaction do
      sender&.update_balance_atomic!(amount: -amount)
      receiver.update_balance_atomic!(amount: amount)
    end
  end

  def validate_sender_balance
    return unless sender

    new_balance = sender.balance - amount
    return if new_balance >= 0

    errors.add(:base, "Not enough balance")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers/account_controller.rb
module Customers
  class AccountController < ApplicationController
    def show
      @transactions = current_customer.transactions
    end
  end
end

app/controllers/customers/application_controller.rb
module Customers
  class ApplicationController < ::ApplicationController
    before_action :authenticate_customer!
  end
end

app/controllers/customers/transactions_controller.rb
module Customers
  class TransactionsController < ApplicationController
    def new
      @transaction_create_request = TransactionCreateRequest.new
    end

    def create
      if transaction_create_request.valid?
        @transaction = build_transfer_transaction!

        if @transaction.save
          flash[:notice] = "Transaction sent"
          return redirect_to root_path
        end
      end

      flash.now[:alert] = "Transaction failed"
      render :new, status: :unprocessable_entity
    end

    private

    def build_transfer_transaction!
      Transaction.new(
        sender: current_customer,
        receiver: transaction_create_request.receiver,
        amount_cents: transaction_create_request.amount_cents,
        transaction_type: "transfer"
      )
    end

    def transaction_create_request
      @transaction_create_request ||= TransactionCreateRequest.new(create_params)
    end

    def create_params
      params.require(:transaction).permit(
        :base_amount,
        :decimal_amount,
        :currency,
        :account_number,
        :account_holder
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/account/show.html.erb
<div class="row">
    <%= link_to "Send new transfer", [:new, :transaction], class: "button is-primary" %>
</div>

<div class="row">
  <table class="table">
    <thead>
      <tr>
        <th>Receiver</th>
        <th>Amount</th>
        <th>Sent on</th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td>
            <span><%= transaction.transaction_type %>:</span>
            <%= transaction.receiver.account_number %>
          </td>

          <td>
            <% if transaction.sender == current_customer %>
              <%= (-1 * transaction.amount).format %>
            <% else %>
              <%= transaction.amount.format %>
            <% end %>
          </td>

          <td>
            <%= l(transaction.created_at, format: :long) %>
          </td>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td>
          <strong>Total: </strong>
        </td>
        <td>
          <strong><%= current_customer.balance.format %></strong>
        </td>
      <tr>
    </tfoot>
  </table>
</div>

app/views/customers/transactions/new.html.erb
<% if @transaction_create_request.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @transaction_create_request.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @transaction&.errors&.any? %>
  <div id="error_explanation">
    <ul>
      <% @transaction.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@transaction_create_request, as: :transaction, url: [:transactions]) do |f| %>
  <div class="field field-group">
    <%= f.label :amount %><br />
    &euro;
    <%= f.number_field :base_amount, autofocus: true %>
    ,
    <%= f.number_field :decimal_amount %>
  </div>

  <div class="field">
    <%= f.label :account_number %>
    <%= f.text_field :account_number %>
  </div>

  <div class="field">
    <%= f.label :account_holder %><br />
    <%= f.text_field :account_holder %>
  </div>

  <div class="actions">
    <%= f.submit "Send!" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigidentityCase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/nav" %>
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div class="notification is-<%= type.to_s == "notice" ? "success" : "warning" %>">
    <button class="delete"></button>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar" role="navigation">
  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", [:root], class: "navbar-item" %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if customer_signed_in? %>
            <%= button_to "Sign out", destroy_customer_session_path,
                          class: "button is-light",
                          method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>